INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('1', 'blue dream', 'Hybrid', '19', 'Creative', './dir/blueDreamNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('2', 'gelato', 'Hybrid', '18', 'Euphoric', './dir/gelatoNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('3', 'sour diesel', 'Sativa', '19', 'Energetic', './dir/sourDieselNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('4', 'wedding cake', 'Hybrid', '22', 'Relaxed', './dir/weddingCakeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('5', 'girl scout cookies', 'Hybrid', '19', 'Hungry', './dir/GSCNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('6', 'purple punch', 'Indica', '20', 'Sleepy', './dir/purplePunchNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('7', 'og kush', 'Hybrid', '18', 'Hungry', './dir/ogKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('8', 'original glue', 'Hybrid', '20', 'Relaxed', './dir/originalGlueNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('9', 'jack herer', 'Sativa', '18', 'Energetic', './dir/jackHererNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('10', 'green crack', 'Sativa', '17', 'Energetic', './dir/greenCrackNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('11', 'granddaddy purp', 'Indica', '18', 'Sleepy', './dir/GrandDaddyNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('12', 'white widow', 'Hybrid', '16', 'Talkative', './dir/whiteWidowNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('13', 'sherbert', 'Hybrid', '19', 'Relaxed', './dir/sherbertNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('14', 'pineapple express', 'Hybrid', '17', 'Energetic', './dir/pineappleNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('15', 'zkittlez', 'Indica', '19', 'Relaxed', './dir/zkittlezNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('16', 'northern lights', 'Indica', '17', 'Sleepy', './dir/northernLightsNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('17', 'mimosa', 'Hybrid', '21', 'Focused', './dir/mimosaNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('18', 'do-si-dos', 'Indica', '21', 'Relaxed', './dir/dosidosNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('19', 'bubba kush', 'Indica', '17', 'Sleepy', './dir/bubbaKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('20', 'durban poison', 'Sativa', '18', 'Energetic', './dir/durbanPoisonNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('21', 'forbidden fruit', 'Indica', '16', 'Relaxed', './dir/forbiddenFruitNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('22', 'chemdog', 'Hybrid', '19', 'Euphoric', './dir/chemdogNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('23', 'ak-47', 'Hybrid', '17', 'Hungry', './dir/ak47New.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('24', 'trainwreck', 'Hybrid', '18', 'Euphoric', './dir/trainwreckNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('25', 'super lemon haze', 'Sativa', '18', 'Energetic', './dir/superLemonHazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('26', 'amnesia haze', 'Sativa', '20', 'Giggly', './dir/amnesiaHazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('27', 'lemon haze', 'Sativa', '19', 'Talkative', './dir/lemonHazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('28', 'stardawg', 'Hybrid', '21', 'Hungry', './dir/stardawgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('29', 'cherry pie', 'Hybrid', '16', 'Giggly', './dir/cherryPieNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('30', 'bruce banner', 'Hybrid', '23', 'Creative', './dir/bruceBannerNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('31', 'strawberry cough', 'Sativa', '18', 'Energetic', './dir/strawberryCoughNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('32', 'blue cookies', 'Hybrid', '20', 'Aroused', './dir/blueCookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('33', 'mendo breath', 'Indica', '19', 'Sleepy', './dir/mendoBreathNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('34', '9 pound hammer', 'Indica', '19', 'Sleepy', './dir/9poundNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('35', 'blueberry', 'Indica', '17', 'Sleepy', './dir/blueberryNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('36', 'super silver haze', 'Sativa', '19', 'Energetic', './dir/superSilverHazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('37', 'mac', 'Hybrid', '21', 'Happy', './dir/MACNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('38', 'ice cream cake', 'Indica', '23', 'Tingly', './dir/iceCreamCakeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('39', 'san fernando valley og', 'Hybrid', '19', 'Focused', './dir/SFVOGNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('40', 'alien og', 'Hybrid', '18', 'Euphoric', './dir/alienNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('41', 'animal cookies', 'Hybrid', '19', 'Relaxed', './dir/animalCookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('42', 'alaskan thunder fuck', 'Sativa', '16', 'Energetic', './dir/alaskanThunderFuckNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('43', 'tangie', 'Sativa', '17', 'Energetic', './dir/tangieNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('44', 'ghost train haze', 'Sativa', '18', 'Energetic', './dir/ghostTrainHazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('45', 'grape ape', 'Indica', '17', 'Sleepy', './dir/grapeApeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('46', 'blue cheese', 'Indica', '17', 'Sleepy', './dir/northernLightsNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('47', 'birthday cake kush', 'Hybrid', '19', 'relaxed', './dir/birthdayCakeKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('48', 'tahoe og kush', 'Hybrid', '18', 'Sleepy', './dir/tahoeKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('49', 'king louis xiii', 'Indica', '21', 'Sleepy', './dir/kingLouisNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('50', 'candyland', 'Sativa', '19', 'Talkative', './dir/candylandNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('51', 'master kush', 'Indica', '18', 'Sleepy', './dir/masterKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('52', 'strawberry banana', 'Hybrid', '21', 'Relaxed', './dir/strawberryBananaNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('53', 'banana kush', 'Hybrid', '19', 'Talkative', './dir/bananaKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('54', 'sundae driver', 'Hybrid', '23', 'Happy', './dir/sundaeDriverNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('55', 'gmo cookies', 'Indica', '21', 'Relaxed', './dir/gmoCookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('56', 'fire og', 'Hybrid', '19', 'Hungry', './dir/fireOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('57', 'purple kush', 'Indica', '16', 'Sleepy', './dir/purpleKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('58', 'cookies and cream', 'Hybrid', '21', 'Happy', './dir/cookiesAndCreamNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('59', 'headband', 'Hybrid', '19', 'Creative', './dir/headbandNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('60', 'g13', 'Indica', '19', 'Euphoric', './dir/g13New.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('61', 'la confidential', 'Indica', '17', 'Sleepy', './dir/laConfidentialNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('62', 'harlequin', 'Sativa', '5', 'Focused', './dir/harlequinNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('63', 'platinum gsc', 'Hybrid', '18', 'Relaxed', './dir/platinumGSChNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('64', 'maui wowie', 'Sativa', '18', 'Energetic', './dir/mauiWowieNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('65', 'platinum og', 'Indica', '20', 'Sleepy', './dir/platinumOg.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('66', 'berry white', 'Indica', '17', 'Talkative', './dir/berryWhiteNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('67', 'purple haze', 'Sativa', '18', 'Creative', './dir/purpleHaze.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('68', 'white fire og', 'Hybrid', '21', 'Tingly', './dir/whiteFireOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('69', 'bubble gum', 'Hybrid', '17', 'Euphoric', './dir/bubbleGumNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('70', 'cinderella 99', 'Hybrid', '16', 'Energetic', './dir/cinderella99New.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('71', 'cookies kush', 'Hybrid', '19', 'Sleepy', './dir/cookiesKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('72', 'zookies', 'Hybrid', '19', 'Focused', './dir/zookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('73', 'cheese', 'Hybrid', '16', 'Hungry', './dir/cheeseNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('74', 'jet fuel', 'Hybrid', '18', 'Focused', './dir/jetFuelNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('75', 'mango kush', 'Hybrid', '20', 'Giggly', './dir/mangoKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('76', 'lsd', 'Hybrid', '17', 'Euphoric', './dir/LSDNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('77', 'lemon og kush', 'Hybrid', '21', 'Hungry', './dir/lemonOgKushKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('78', 'grease monkey', 'Hybrid', '23', 'Relaxed', './dir/greaseMonkeyNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('79', 'kosher kush', 'Indica', '20', 'Sleepy', './dir/kosherKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('80', 'critical kush', 'Indica', '18', 'Sleepy', './dir/criticalKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('81', 'lemon kush', 'Hybrid', '20', 'Giggly', './dir/lemonKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('82', 'white rhino', 'Indica', '17', 'Sleepy', './dir/whiteRhinoNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('83', 'pink kush', 'Hybrid', '18', 'Hungry', './dir/pinkKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('84', 'acdc', 'Hybrid', '14', 'Focused', './dir/ACDCNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('85', 'slurricane', 'Indica', '18', 'Relaxed', './dir/slurricaneNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('86', 'gelato 33', 'Hybrid', '19', 'Uplifted', './dir/gelato33New.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('87', 'ghost og', 'Indica', '16', 'Relaxed', './dir/ghostOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('88', 'thin mint gsc', 'Hybrid', '21', 'Euphoric', './dir/thinMintNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('89', 'blackberry kush', 'Hybrid', '19', 'Sleepy', './dir/blackberryKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('90', 'g13', 'Indica', '19', 'Euphoric', './dir/g13New.png');