INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('1', 'blue dream', 'Hybrid', '19', 'Creative', './dir/blueDreamNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('2', 'gelato', 'Hybrid', '18', 'Euphoric', './dir/gelatoNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('3', 'sour diesel', 'Sativa', '19', 'Energetic', './dir/sourDieselNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('4', 'wedding cake', 'Hybrid', '22', 'Relaxed', './dir/weddingCakeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('5', 'girl scout cookies', 'Hybrid', '19', 'Hungry', './dir/GSCNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('6', 'purple punch', 'Indica', '20', 'Sleepy', './dir/purplePunchNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('7', 'og kush', 'Hybrid', '18', 'Hungry', './dir/ogKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('8', 'original glue', 'Hybrid', '20', 'Relaxed', './dir/originalGlueNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('9', 'jack herer', 'Sativa', '18', 'Energetic', './dir/jackHererNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('10', 'green crack', 'Sativa', '17', 'Energetic', './dir/greenCrackNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('11', 'granddaddy purp', 'Indica', '18', 'Sleepy', './dir/GrandDaddyNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('12', 'white widow', 'Hybrid', '16', 'Talkative', './dir/whiteWidowNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('13', 'sherbert', 'Hybrid', '19', 'Relaxed', './dir/sherbertNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('14', 'pineapple express', 'Hybrid', '17', 'Energetic', './dir/pineappleNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('15', 'zkittlez', 'Indica', '19', 'Relaxed', './dir/zkittlezNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('16', 'northern lights', 'Indica', '17', 'Sleepy', './dir/northernLightsNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('17', 'mimosa', 'Hybrid', '21', 'Focused', './dir/mimosaNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('18', 'do-si-dos', 'Indica', '21', 'Relaxed', './dir/dosidosNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('19', 'bubba kush', 'Indica', '17', 'Sleepy', './dir/bubbaKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('20', 'durban poison', 'Sativa', '18', 'Energetic', './dir/durbanPoisonNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('21', 'forbidden fruit', 'Indica', '16', 'Relaxed', './dir/forbiddenFruitNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('22', 'chemdog', 'Hybrid', '19', 'Euphoric', './dir/chemdogNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('23', 'ak-47', 'Hybrid', '17', 'Hungry', './dir/ak47New.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('24', 'trainwreck', 'Hybrid', '18', 'Euphoric', './dir/trainwreckNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('25', 'super lemon haze', 'Sativa', '18', 'Energetic', './dir/superLemonHazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('26', 'amnesia haze', 'Sativa', '20', 'Giggly', './dir/amnesiaHazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('27', 'lemon haze', 'Sativa', '19', 'Talkative', './dir/lemonHazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('28', 'stardawg', 'Hybrid', '21', 'Hungry', './dir/stardawgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('29', 'cherry pie', 'Hybrid', '16', 'Giggly', './dir/cherryPieNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('30', 'bruce banner', 'Hybrid', '23', 'Creative', './dir/bruceBannerNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('31', 'strawberry cough', 'Sativa', '18', 'Energetic', './dir/strawberryCoughNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('32', 'blue cookies', 'Hybrid', '20', 'Aroused', './dir/blueCookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('33', 'mendo breath', 'Indica', '19', 'Sleepy', './dir/mendoBreathNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('34', '9 pound hammer', 'Indica', '19', 'Sleepy', './dir/9poundNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('35', 'blueberry', 'Indica', '17', 'Sleepy', './dir/blueberryNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('36', 'super silver haze', 'Sativa', '19', 'Energetic', './dir/superSilverHazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('37', 'mac', 'Hybrid', '21', 'Happy', './dir/MACNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('38', 'ice cream cake', 'Indica', '23', 'Tingly', './dir/iceCreamCakeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('39', 'san fernando valley og', 'Hybrid', '19', 'Focused', './dir/SFVOGNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('40', 'alien og', 'Hybrid', '18', 'Euphoric', './dir/alienNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('41', 'animal cookies', 'Hybrid', '19', 'Relaxed', './dir/animalCookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('42', 'alaskan thunder fuck', 'Sativa', '16', 'Energetic', './dir/alaskanThunderFuckNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('43', 'tangie', 'Sativa', '17', 'Energetic', './dir/tangieNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('44', 'ghost train haze', 'Sativa', '18', 'Energetic', './dir/ghostTrainHazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('45', 'grape ape', 'Indica', '17', 'Sleepy', './dir/grapeApeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('46', 'blue cheese', 'Indica', '17', 'Sleepy', './dir/northernLightsNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('47', 'birthday cake kush', 'Hybrid', '19', 'relaxed', './dir/birthdayCakeKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('48', 'tahoe og kush', 'Hybrid', '18', 'Sleepy', './dir/tahoeKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('49', 'king louis xiii', 'Indica', '21', 'Sleepy', './dir/kingLouisNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('50', 'candyland', 'Sativa', '19', 'Talkative', './dir/candylandNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('51', 'master kush', 'Indica', '18', 'Sleepy', './dir/masterKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('52', 'strawberry banana', 'Hybrid', '21', 'Relaxed', './dir/strawberryBananaNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('53', 'banana kush', 'Hybrid', '19', 'Talkative', './dir/bananaKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('54', 'sundae driver', 'Hybrid', '23', 'Happy', './dir/sundaeDriverNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('55', 'gmo cookies', 'Indica', '21', 'Relaxed', './dir/gmoCookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('56', 'fire og', 'Hybrid', '19', 'Hungry', './dir/fireOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('57', 'purple kush', 'Indica', '16', 'Sleepy', './dir/purpleKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('58', 'cookies and cream', 'Hybrid', '21', 'Happy', './dir/cookiesAndCreamNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('59', 'headband', 'Hybrid', '19', 'Creative', './dir/headbandNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('60', 'g13', 'Indica', '19', 'Euphoric', './dir/g13New.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('61', 'la confidential', 'Indica', '17', 'Sleepy', './dir/laConfidentialNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('62', 'harlequin', 'Sativa', '5', 'Focused', './dir/harlequinNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('63', 'platinum gsc', 'Hybrid', '18', 'Relaxed', './dir/platinumGSChNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('64', 'maui wowie', 'Sativa', '18', 'Energetic', './dir/mauiWowieNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('65', 'platinum og', 'Indica', '20', 'Sleepy', './dir/platinumOg.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('66', 'berry white', 'Indica', '17', 'Talkative', './dir/berryWhiteNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('67', 'purple haze', 'Sativa', '18', 'Creative', './dir/purpleHaze.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('68', 'white fire og', 'Hybrid', '21', 'Tingly', './dir/whiteFireOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('69', 'bubble gum', 'Hybrid', '17', 'Euphoric', './dir/bubbleGumNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('70', 'cinderella 99', 'Hybrid', '16', 'Energetic', './dir/cinderella99New.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('71', 'cookies kush', 'Hybrid', '19', 'Sleepy', './dir/cookiesKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('72', 'zookies', 'Hybrid', '19', 'Focused', './dir/zookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('73', 'cheese', 'Hybrid', '16', 'Hungry', './dir/cheeseNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('74', 'jet fuel', 'Hybrid', '18', 'Focused', './dir/jetFuelNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('75', 'mango kush', 'Hybrid', '20', 'Giggly', './dir/mangoKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('76', 'lsd', 'Hybrid', '17', 'Euphoric', './dir/LSDNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('77', 'lemon og kush', 'Hybrid', '21', 'Hungry', './dir/lemonOgKushKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('78', 'grease monkey', 'Hybrid', '23', 'Relaxed', './dir/greaseMonkeyNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('79', 'kosher kush', 'Indica', '20', 'Sleepy', './dir/kosherKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('80', 'critical kush', 'Indica', '18', 'Sleepy', './dir/criticalKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('81', 'lemon kush', 'Hybrid', '20', 'Giggly', './dir/lemonKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('82', 'white rhino', 'Indica', '17', 'Sleepy', './dir/whiteRhinoNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('83', 'pink kush', 'Hybrid', '18', 'Hungry', './dir/pinkKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('84', 'acdc', 'Hybrid', '14', 'Focused', './dir/ACDCNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('85', 'slurricane', 'Indica', '18', 'Relaxed', './dir/slurricaneNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('86', 'gelato 33', 'Hybrid', '19', 'Uplifted', './dir/gelato33New.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('87', 'ghost og', 'Hybrid', '20', 'Relaxed', './dir/ghostOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('88', 'thin mint gsc', 'Hybrid', '19', 'Euphoric', './dir/thinMintNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('89', 'blackberry kush', 'Indica', '17', 'Sleepy', './dir/blackberryKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('90', 'wedding crasher', 'Hybrid', '22', 'Euphoric', './dir/weddingCrasherNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('91', 'acapulco gold', 'Sativa', '18', 'Creative', './dir/acapulcoGoldNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('92', 'superglue', 'Hybrid', '20', 'Relaxed', './dir/superglueNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('93', 'afghan kush', 'Indica', '17', 'Hungry', './dir/afghanKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('94', 'golden goat', 'Hybrid', '19', 'Energetic', './dir/goldenGoatNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('95', 'khalifa kush', 'Hybrid', '20', 'Giggly', './dir/khalifaKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('96', 'gods gift', 'Indica', '16', 'Sleepy', './dir/godsGiftNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('97', 'banana og', 'Hybrid', '21', 'Hungry', './dir/bananaOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('98', 'lemon skunk', 'Hybrid', '19', 'Happy', './dir/lemonSkunkNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('99', 'chocolope', 'Sativa', '16', 'Energetic', './dir/chocolopeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('100', 'sour tangie', 'Sativa', '18', 'Energetic', './dir/sourTangieNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('101', 'super sour diesel', 'Sativa', '20', 'Creative', './dir/superSourDieselNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('102', 'platinum kush', 'Indica', '19', 'Hungry', './dir/platniumKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('103', 'orange cookies', 'Hybrid', '16', 'Happy', './dir/orangeCookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('104', 'purple urkle', 'Indica', '16', 'Sleepy', './dir/purpleUrkleNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('105', 'tangerine dream', 'Hybrid', '17', 'Energetic', './dir/tangerineDreamNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('106', 'gorilla cookies', 'Hybrid', '20', 'Relaxed', './dir/gorillaCookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('107', 'amnesia', 'Sativa', '17', 'Giggly', './dir/amnesiaNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('108', 'death star', 'Indica', '20', 'Sleepy', './dir/deathStarNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('109', 'hindu kush', 'Indica', '18', 'Sleepy', './dir/hinduKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('110', 'white buffalo', 'Sativa', '19', 'Euphoric', './dir/whiteBuffaloNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('111', 'clementine', 'Sativa', '17', 'Energetic', './dir/clementineNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('112', 'black diamond', 'Indica', '18', 'Hungry', './dir/blackDiamondNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('113', 'larry og', 'Hybrid', '18', 'Hungry', './dir/larryOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('114', 'nyc diesel', 'Hybrid', '18', 'Talkative', './dir/nycDieselNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('115', 'silver haze', 'Sativa', '22', 'Talkative', './dir/silverHazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('116', 'fruity pebbles og', 'Hybrid', '17', 'Giggly', './dir/fruityPebblesOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('117', 'blueberry kush', 'Indica', '18', 'Sleepy', './dir/blueberryKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('118', 'blueberry muffin', 'Hybrid', '18', 'Relaxed', './dir/blueberryMuffinNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('119', '24k gold', 'Hybrid', '21', 'Happy', './dir/24kGoldNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('120', 'haze', 'Hybrid', '22', 'Energetic', './dir/hazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('121', 'skunk 1', 'Hybrid', '22', 'Hungry', './dir/skunk1New.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('122', 'critical mass', 'Indica', '18', 'Sleepy', './dir/criticalMassNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('123', 'sour og', 'Hybrid', '20', 'Talkative', './dir/sourOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('124', 'venom og', 'Hybrid', '20', 'Tingly', './dir/venomOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('125', 'cannatonic', 'Hybrid', '6', 'Relaxed', './dir/cannatonicNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('126', 'lemon cake', 'Sativa', '23', 'Uplifted', './dir/lemonCakeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('127', 'afghani', 'Indica', '16', 'Sleepy', './dir/afghaniNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('128', 'true og', 'Indica', '19', 'Sleepy', './dir/trueOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('129', 'xj-13', 'Hybrid', '17', 'Creative', './dir/xj13New.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('130', 'key lime pie', 'Hybrid', '18', 'Tingly', './dir/keyLimePieNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('131', 'paradise waits', 'Hybrid', '28', 'Creative', './dir/paradiseWaitsNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('132', 'member berry', 'Hybrid', '28', 'Euphoric', './dir/memberBerryNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('133', 'jillybean', 'Hybrid', '16', 'Energetic', './dir/jillybeanNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('134', 'the white', 'Hybrid', '21', 'Euphoric', './dir/theWhiteNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('135', 'papaya', 'Indica', '15', 'Sleepy', './dir/papayaNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('136', 'tropicana cookies', 'Sativa', '17', 'Aroused', './dir/tropicanaCookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('137', 'moby dick', 'Sativa', '16', 'Talkative', './dir/mobyDickNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('138', 'ice cream', 'Hybrid', '19', 'Hungry', './dir/iceCreamNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('139', 'gushers', 'Hybrid', '25', 'Euphoric', './dir/gushersNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('140', 'island sweet skunk', 'Sativa', '16', 'Energetic', './dir/islandSweetSkunkNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('141', 'mk ultra', 'Indica', '19', 'Sleepy', './dir/mkUltraNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('142', 'kandy kush', 'Hybrid', '18', 'Hungry', './dir/kandyKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('143', 'holy grail kush', 'Hybrid', '20', 'Relaxed', './dir/holyGrailKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('144', 'blue diesel', 'Hybrid', '17', 'Giggly', './dir/blueDieselNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('145', 'fruit punch', 'Sativa', '16', 'Energetic', './dir/fruitPunchNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('146', 'platinum bubba kush', 'Indica', '15', 'Hungry', './dir/platniumBubbaKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('147', 'dutch treat', 'Hybrid', '20', 'Euphoric', './dir/dutchTreatNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('148', 'dutch hawaiian', 'Sativa', '18', 'Uplifted', './dir/dutchHawaiianNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('149', 'lambs bread', 'Sativa', '17', 'Creative', './dir/lambsBreadNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('150', 'orange kush', 'Indica', '17', 'Hungry', './dir/orangeKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('151', 'super skunk', 'Indica', '15', 'Hungry', './dir/superSkunkNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('152', 'agent orange', 'Hybrid', '15', 'Energetic', './dir/agentOrangeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('153', 'chernobyl', 'Hybrid', '18', 'Energetic', './dir/chernobylNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('154', 'watermelon', 'Indica', '29', 'Sleepy', './dir/watermelonNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('155', 'grapefruit', 'Sativa', '17', 'Energetic', './dir/grapefruitNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('156', 'black jack', 'Hybrid', '19', 'Talkative', './dir/blackJackNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('157', 'gorilla grapes', 'Hybrid', '17', 'Happy', './dir/gorillaGrapesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('158', 'death bubba', 'Indica', '26', 'Sleepy', './dir/deathBubbaNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('159', 'diamond og', 'Indica', '19', 'Sleepy', './dir/diamondOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('160', 'gary payton', 'Hybrid', '23', 'Happy', './dir/garyPaytonNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('161', 'sensi star', 'Indica', '18', 'Sleepy', './dir/sensiStarNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('162', 'monster cookies', 'Indica', '20', 'Sleepy', './dir/monsterCookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('163', 'cereal milk', 'Hybrid', '21', 'Relaxed', './dir/cerealMilkNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('164', 'cotton candy kush', 'Hybrid', '17', 'Giggly', './dir/cottonCandyKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('165', 'blackwater', 'Indica', '19', 'Sleepy', './dir/blackWaterNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('166', 'space queen', 'Hybrid', '18', 'Uplifted', './dir/spaceQueenNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('167', 'godfather og', 'Indica', '18', 'Sleepy', './dir/godfatherOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('168', 'shishkaberry', 'Indica', '17', 'Sleepy', './dir/shishkaberryNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('169', 'mango', 'Indica', '17', 'Hungry', './dir/mangoNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('170', 'triangle kush', 'Indica', '20', 'Tingly', './dir/triangleKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('171', 'blackberry', 'Hybrid', '17', 'Aroused', './dir/blackberryNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('172', '3 kings', 'Hybrid', '19', 'Aroused', './dir/3KingsNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('173', 'gelato 41', 'Hybrid', '20', 'Relaxed', './dir/gelato41New.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('174', 'juicy fruit', 'Hybrid', '17', 'Happy', './dir/juicyFruitNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('175', 'lemon tree', 'Hybrid', '18', 'Talkative', './dir/lemonTreeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('176', 'motorbreath', 'Hybrid', '26', 'Euphoric', './dir/motorbreathNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('177', 'mr. nice', 'Indica', '17', 'Sleepy', './dir/mrNiceNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('178', 'flo', 'Hybrid', '17', 'Energetic', './dir/floNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('179', 'romulan', 'Indica', '16', 'Sleepy', './dir/romulanNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('180', 'rockstar', 'Indica', '18', 'Sleepy', './dir/rockstarNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('181', 'pineapple kush', 'Hybrid', '18', 'Giggly', './dir/pineappleKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('182', 'og 18', 'Hybrid', '22', 'Relaxed', './dir/og18New.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('183', 'lemon meringue', 'Sativa', '20', 'Creative', './dir/lemonMeringueNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('184', 'orange creamsicle', 'Hybrid', '18', 'Happy', './dir/orangeCreamsicleNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('185', 'mango haze', 'Sativa', '18', 'Uplifted', './dir/mangoHazeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('186', 'obama kush', 'Indica', '18', 'Relaxed', './dir/obamaKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('187', 'laughing buddha', 'Sativa', '21', 'Giggly', './dir/laughingBuddhaNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('188', 'blueberry headband', 'Hybrid', '18', 'Talkative', './dir/blueberryHeadbandNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('189', 'orange crush', 'Hybrid', '19', 'Talkative', './dir/orangeCrushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('190', 'cheese quake', 'Hybrid', '18', 'Tingly', './dir/cheeseQuakeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('191', 'god bud', 'Indica', '16', 'Sleepy', './dir/godBudNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('192', 'blue zkittlez', 'Indica', '16', 'Aroused', './dir/blueZkittlezNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('193', 'rainbow', 'Hybrid', '18', 'Tingly', './dir/rainbowNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('194', 'sour kush', 'Hybrid', '19', 'Giggly', './dir/sourKushNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('195', 'white russian', 'Hybrid', '17', 'Euphoric', './dir/whiteRussianNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('196', 'pineapple', 'Hybrid', '18', 'Happy', './dir/pineappleNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('197', 'sweet tooth', 'Indica', '18', 'Euphoric', './dir/sweethToothNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('198', 'white tahoe cookies', 'Indica', '22', 'Aroused', './dir/whiteTahoeCookiesNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('199', 'northern hashplant', 'Indica', '18', 'Relaxed', './dir/northernHashplantNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('200', 'purple trainwreck', 'Hybrid', '16', 'Euphoric', './dir/purpleTrainwreckNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('201', 'dogwalker og', 'Hybrid', '23', 'Tingly', './dir/dogWalkerOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('202', 'jgr', 'Indica', '19', 'Relaxed', './dir/jgrNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('203', 'lemon diesel', 'Hybrid', '18', 'Focused', './dir/lemonDieselNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('204', 'great white shark', 'Sativa', '15', 'Energetic', './dir/greatWhiteSharkNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('205', 'ogkb', 'Hybrid', '24', 'Tingly', './dir/ogkbNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('206', 'jungle cake', 'Hybrid', '25', 'Euphoric', './dir/jungleCakeNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('207', 'pineapple chunk', 'Hybrid', '18', 'Tingly', './dir/pineappleChunkNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('208', 'xxx og', 'Indica', '20', 'Sleepy', './dir/xxxOgNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('209', 'purple diesel', 'Hybrid', '14', 'Sleepy', './dir/purpleDieselNew.png');
INSERT INTO weed_strains (strain_ID, strain_Name, strain_type, thc_percent, strain_feeling, strain_image)VALUES ('210', 'nuken', 'Indica', '22', 'Relaxed', './dir/nukenNew.png');